### ISSUE TITLE
Publishing changes from within view updates is not allowed, this will cause undefined behavior.

### ISSUE THREAD

**Issue by BredBurr** [ivanvorobei/SPConfetti#11]
Sources -> SPConfetti -> SwiftUI -> SPConfettiModifier line 102

<img width="1125" alt="Screenshot" src="https://user-images.githubusercontent.com/124914915/217890460-e8cc5285-59d0-4c91-b4ad-9ab3e278cbf4.png">

Are you sure it's safe to use?

**Comment by BredBurr** [comment]
Maybe put it in a DispatchQueue.main.async?

**Comment by ivanvorobei** [comment]
Sorry for delay. Do you think mistake with thread or maybe you call in background?

**Comment by gongzhang** [comment]
Sorry my mistake. I believe the `isPresented.wrappedValue = false` statement in `stop()` should be changed to:

```swift
if isPresented.wrappedValue != false {
    isPresented.wrappedValue = false
}
```

This should fix the warning.
