### ISSUE TITLE
Displaying over Sheets

### ISSUE THREAD

**Issue by einlichtvogel** [ivanvorobei/SPConfetti#2]
**Describe the problem that you catch**
A clear and concise description of what you want to do.
 Hey, is it possible to display the confetti over a sheet?
 After the first start of the app and displaying the sheet, the confetti is getting displayed over it, after reopening the sheet, it's getting displayed behind it. It's kinda problematic to share a video with you, because I have to blur out all personal data, but If you really need it, I can do it.
 I would be glad if you could help :)
 Thanks!

**Comment by ivanvorobei** [comment]
@blockiyt i think it's available. You should place confetti at the top layer on your window.

**Comment by einlichtvogel** [comment]
<img width="430" alt="Bildschirmfoto 2021-09-30 um 16 12 23" src="https://user-images.githubusercontent.com/65811753/135471706-cf303130-150e-4f6d-8ad5-880ab659d8dc.png">
I'm using it in a Button, in a VStack in a NavigationView.
What do you mean with placing in on the top?
Sorry haha, but I am new in this area 👀

**Comment by ivanvorobei** [comment]
Ah, `SwiftUI`. In it I think no available.

**Comment by einlichtvogel** [comment]
But if I make a UIViewRepresentable, would this work?

**Comment by ivanvorobei** [comment]
I can't help you with it, I leave issue open - maybe somebody home more experience in `SwiftUI`.

**Comment by einlichtvogel** [comment]
Ok, but I think I found the problem. The confetti restarts there, where it got stopped. So if I let the confetti completely rain down in the sheet, it works, but if I close it, it end on an other view and starts there again.

**Comment by gongzhang** [comment]
~~Similar issue. Got this warning:~~
```
SPConfetti - Confetti already releases. Please, call `stopAnimating` func before start new animation. For now this call don't have any effect.
```

**Comment by gongzhang** [comment]
@ivanvorobei Hi, Ivan, 😄

I'm trying to fix this issuse. Please review https://github.com/ivanvorobei/SPConfetti/pull/6/commits/740d4d794c269361d27648b15c5879cb0f992ea2 , thanks.
