### ISSUE TITLE
Colors are wrong

### ISSUE THREAD

**Issue by ljs19923** [ivanvorobei/SPConfetti#4]
Hi, 
When I choose colors, the result is not good, all displaying colors cells are more dark, than the original color chosen.
For example a yellow this one, FCB700, become totally orange in cells.

**Comment by ivanvorobei** [comment]
Hello, hex that you attached really darker. On right - is system yellow. Can you explain more? Did you set `.systemYellow` and see orange color? or which color did you set? 

<img width="568" alt="Screenshot 2021-11-16 at 12 58 19" src="https://user-images.githubusercontent.com/10995774/141963758-461e0b61-d127-4fa1-afb7-5d2a66a5efa7.png">
