### ISSUE TITLE
Maybe apply 3D transforms to particles to achieve better effects?

### ISSUE THREAD

**Issue by gongzhang** [ivanvorobei/SPConfetti#5]
**Is your feature request related to a problem? Please describe.**
I really like the confetti effect in iMessage. It would be nice if SPConfetti could do something similar.

**Describe the solution you'd like**
👍 Checkout this repo: [bryce-co/RecreatingiMessageConfetti](https://github.com/bryce-co/RecreatingiMessageConfetti)

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by ivanvorobei** [comment]
Thanks for idea, I will check how can add it.

**Comment by ivanvorobei** [comment]
Sorry for delay
Added in `1.4.0` version
