### ISSUE TITLE
Failed to archive build with latest SwiftUI code

### ISSUE THREAD

**Issue by gongzhang** [ivanvorobei/SPConfetti#7]
**Describe the bug**
Hi, Ivan, I just noticed the latest SwiftUI code break the SPM build. (-｡-;

**To Reproduce**

1. In Xcode, select the "iOS SwiftUI Example" target and build for "Any iOS Device"
2. Product menu > run Archive
3. The compiler will report errors related to SwiftUI symbols.

![image](https://user-images.githubusercontent.com/4470629/143689713-194e2b43-614c-410a-8fa6-c985d163bc51.png)

**Comment by gongzhang** [comment]
I found that you can fix it by simply change the deployment target from `v10` to `v11` in `Package.swift`:

```swift
// swift-tools-version:5.3

import PackageDescription

let package = Package(
    name: "SPConfetti",
    platforms: [
        .iOS(.v10), .tvOS(.v10) // <== ✅ .iOS(.v11) , .tvOS(.v10)
    ],
    ...
```

Maybe helpful:
https://forums.swift.org/t/platform-per-target/29253

**Comment by ivanvorobei** [comment]
You right, I changed target for cocoapods before, but forgot about SPM. In version `1.3.3` it has been fixed, please, update.
