### ISSUE TITLE
SPM: Couldn’t check out revision "fd172fe3cc07572e546942cb175b16e549fc3e1a"

### ISSUE THREAD

**Issue by gongzhang** [ivanvorobei/SPConfetti#8]
**Details**
 - Xcode 13.4
 - Framework Version 1.4
 - Installed via SPM
 
**Describe the Bug**

Hi Ivan,

I have encountered a strange problem. When I add Package Dependencies in Xcode's Project Setting, the SPM seems to resolve the latest `SPConfetti` to an incorrect revision. I use the Xcode default settings when adding dependency.

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/4470629/171360688-378dd631-a725-4946-93ce-3ec00a8b9e08.png">

However, the revision in the `Package.resolved` file points to `fd172fe3cc07572e546942cb175b16e549fc3e1a`, but this commit seems to be incorrect. There is also a warning on GitHub page for this revision: [`fd172fe3cc07572e546942cb175b16e549fc3e1a`](https://github.com/ivanvorobei/SPConfetti/commit/fd172fe3cc07572e546942cb175b16e549fc3e1a).

```js
// Package.resolved
      {
        "package": "SPConfetti",
        "repositoryURL": "https://github.com/ivanvorobei/SPConfetti.git",
        "state": {
          "branch": null,
          "revision": "fd172fe3cc07572e546942cb175b16e549fc3e1a", // <=== 🤔
          "version": "1.4.0"
        }
      },
```

This issue can cause SPM to fail to checkout dependencies when building with CI. I can mannually edit `Package.resolve` to workaround the issue. But it will be great to fix it from the repo.

**Comment by ivanvorobei** [comment]
Problem is still with you?

**Comment by gongzhang** [comment]
@ivanvorobei I believe there is no more problem in 1.4.1. 😉
