### ISSUE TITLE
iOS 15.5 Bug: Confetti does not appear

### ISSUE THREAD

**Issue by Rogue85** [ivanvorobei/SPConfetti#9]
**Details**
 - iOS 15.5
 - SPConfetti 1.4.0
 - Installed via Cocoapods
 
**Describe the Bug**
Confetti does not appear on devices with iOS 15.5. The startAnimating call is simply ignored without errors.

**Comment by ashishj-optimus** [comment]
Looks like this is still not fixed. Nothing shows up iOS 16.

**Comment by ivanvorobei** [comment]
@ashishj-optimus please, try example project
